# Generated by Django 3.2.4 on 2024-01-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_badge'),
        ('users', '0002_profile_total_contribution_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.badge'),
        ),
    ]
