# Generated by Django 3.2.4 on 2024-01-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(default='no_icon.png', upload_to=''),
        ),
    ]
