# Generated by Django 3.2.4 on 2024-01-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
