# Generated by Django 3.2.4 on 2024-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20240106_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashags',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Hashtag'),
        ),
    ]
