# Generated by Django 3.2.4 on 2024-01-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_hashags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashags',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='posts.Hashtag'),
        ),
    ]
