# Generated by Django 3.2.4 on 2024-01-08 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_auto_20240108_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='power',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
