# Generated by Django 3.2.4 on 2024-01-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20240117_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='Profile',
            new_name='profile',
        ),
    ]
