# Generated by Django 3.2.4 on 2024-01-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_rename_profile_postlike_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
